import { resolveBin, run } from '@src/proc.js';
import type { RunFn } from '@src/proc.js';
import { detail, warn } from '@src/log.js';
import { createHeartbeat, parseClaudeLine, withHeartbeat } from '@src/progress.js';
import type { ProgressOptions } from '@src/progress.js';
import type { ClaudeTurnResult, ContextUsage, Effort, PermissionMode, TokenUsage } from '@src/types.js';

let cachedBin: string | null = null;

export function claudeBin(): string {
  cachedBin ??= resolveBin('claude', {
    envVar: 'VIBE_CLAUDE_BIN',
    fallbacks: [
      'C:/Program Files/nodejs/node_modules/@anthropic-ai/claude-code/bin/claude.exe',
      '~/AppData/Roaming/npm/node_modules/@anthropic-ai/claude-code/bin/claude.exe',
      '~/.local/bin/claude',
      '/usr/local/bin/claude',
    ],
  });
  return cachedBin;
}

let sessionArgs: readonly string[] = [];

/**
 * Arguments every turn in this run must carry - currently the `--settings`
 * file holding the environment repair.
 *
 * Set once by preflight rather than threaded through each call site. An
 * earlier version returned the repair args from preflight and left callers to
 * pass them; nothing did, so the repair applied only to preflight's own probe
 * turns and the implementer had to patch its own PATH by hand. Applying them
 * inside `claudeTurn` makes that omission impossible, including for the
 * rotation turns issued from context.ts.
 */
export function setSessionArgs(args: readonly string[]): void {
  sessionArgs = args;
}

export interface ClaudeTurnOptions {
  prompt: string;
  sessionId: string;
  resume: boolean;
  permissionMode: PermissionMode;
  model: string;
  effort: Effort;
  cwd: string;
  jsonSchema?: object | undefined;
  tools?: readonly string[] | undefined;
  timeoutMs: number;
  /** Live progress. Omitted disables it entirely, which is what preflight wants. */
  progress?: ProgressOptions | undefined;
}

function isRecord(v: unknown): v is Record<string, unknown> {
  return typeof v === 'object' && v !== null && !Array.isArray(v);
}

function num(v: unknown): number {
  return typeof v === 'number' && Number.isFinite(v) ? v : 0;
}

/**
 * One Claude turn.
 *
 * The session id is generated by the caller up front so it is known before the
 * first call; later turns pass `resume: true` with the same id. Permission mode
 * is per-invocation, which is how a read-only plan session becomes a
 * bypassPermissions implementation session without losing the plan from context.
 *
 * **What counts as a failed turn.** The `result` envelope, not the exit status:
 * no stdout, no result event, or a result the CLI itself marks as an error. A
 * non-zero exit alongside a complete successful envelope means teardown failed
 * after the work was done - and the envelope is where the cost and usage the run
 * depends on live - so it is warned about and accepted rather than throwing away
 * a turn that has already been paid for. Deterministic tools are judged the
 * other way round; see git.ts and verify.ts.
 *
 * `exec` is injected so the adapter's boundary with the heartbeat can be tested
 * without spawning a real agent, as `rotateSession` and `ClaudeProbeExecutor`
 * already are.
 */
export async function claudeTurn(
  options: ClaudeTurnOptions,
  exec: RunFn = run,
): Promise<ClaudeTurnResult> {
  const { prompt, sessionId, resume, permissionMode, model, effort, cwd, jsonSchema, tools, timeoutMs } =
    options;

  // stream-json rather than json: the aggregate `usage` on the result envelope
  // sums every API request in the turn, so it cannot measure live context. The
  // per-message usage in the stream can. See extractUsage below.
  const args: string[] = [
    '-p',
    '--output-format', 'stream-json',
    '--verbose',
    '--permission-mode', permissionMode,
  ];
  args.push(resume ? '--resume' : '--session-id', sessionId);
  args.push('--model', model, '--effort', effort);
  if (jsonSchema) args.push('--json-schema', JSON.stringify(jsonSchema));
  args.push(...sessionArgs);
  // Variadic flags must come last: they greedily consume following tokens.
  if (tools && tools.length > 0) args.push('--tools', ...tools);

  detail(`claude ${args.filter((a) => !a.startsWith('{')).join(' ')}`);

  const heartbeat = options.progress
    ? createHeartbeat({ ...options.progress, parse: parseClaudeLine, unit: 'tool use' })
    : null;
  // Validation runs inside the heartbeat's work, not after it: the end-of-turn
  // flush is a claim that the turn completed, and while only `run()` was wrapped
  // a turn whose output failed every check below still persisted as one that
  // had.
  return withHeartbeat(heartbeat, async () => {
    const { code, stdout, stderr } = await exec(claudeBin(), args, {
      input: prompt,
      cwd,
      timeoutMs,
      ...(heartbeat === null ? {} : { onLine: heartbeat.onLine }),
    });

    if (!stdout.trim()) {
      throw new Error(`claude produced no output (exit ${code}). stderr:\n${stderr.slice(-2000)}`);
    }

    const { result: parsed, lastAssistantUsage } = parseStream(stdout);
    if (!parsed) {
      throw new Error(
        `claude emitted no result event (exit ${code}):\n${stdout.slice(-2000)}`,
      );
    }

    if (parsed['is_error'] === true || parsed['subtype'] !== 'success') {
      const subtype = typeof parsed['subtype'] === 'string' ? parsed['subtype'] : 'unknown';
      const status = parsed['api_error_status'];
      const result = parsed['result'];
      const detail = `${String(status ?? '')} ${String(result ?? '')}`.trim();

      const limit = detectRateLimit(`${detail}\n${stderr}`);
      if (limit) throw limit;

      throw new Error(`claude turn failed (${subtype}): ${detail}`);
    }

    const denialsRaw = parsed['permission_denials'];
    const text = typeof parsed['result'] === 'string' ? parsed['result'] : '';

    if (code !== 0) {
      // Logged, not thrown: see the exit-status note above. Worth saying out
      // loud so that if it ever becomes routine, it is visible in the run log
      // rather than being mistaken for an oversight.
      warn(`claude exited ${String(code)} but returned a complete successful result; accepting it.`);
    }

    return {
      text,
      costUsd: num(parsed['total_cost_usd']),
      sessionId: typeof parsed['session_id'] === 'string' ? parsed['session_id'] : sessionId,
      denials: Array.isArray(denialsRaw) ? denialsRaw : [],
      numTurns: num(parsed['num_turns']),
      usage: extractUsage(parsed, lastAssistantUsage),
      tokens: extractTokens(parsed),
    };
  });
}

/**
 * Total tokens moved by the turn. The envelope's aggregated `usage` is exactly
 * right for this - it is only wrong for measuring live context, which is what
 * extractUsage handles separately.
 */
function extractTokens(envelope: Record<string, unknown>): TokenUsage {
  const usage = envelope['usage'];
  if (!isRecord(usage)) {
    return { input: 0, output: 0, cacheRead: 0, cacheCreation: 0, total: 0 };
  }
  const input = num(usage['input_tokens']);
  const output = num(usage['output_tokens']);
  const cacheRead = num(usage['cache_read_input_tokens']);
  const cacheCreation = num(usage['cache_creation_input_tokens']);
  return {
    input,
    output,
    cacheRead,
    cacheCreation,
    total: input + output + cacheRead + cacheCreation,
  };
}

/**
 * Subscription rate limit, as distinct from an ordinary failure.
 *
 * On a plan with overage disabled this is the wall a long unattended run hits -
 * not a spend limit. It is recoverable by waiting, so it gets its own type
 * rather than being flattened into a generic error.
 */
export class RateLimitError extends Error {
  constructor(message: string, readonly resetsAt: Date | null) {
    super(message);
    this.name = 'RateLimitError';
  }
}

const RATE_LIMIT_RE =
  /usage limit reached|rate.?limit|429|too many requests|quota exceeded|limit will reset/i;
/** Claude reports the reset as a unix epoch (seconds) in the limit message. */
const RESET_EPOCH_RE = /\b(1[0-9]{9})\b/;
const RESET_ISO_RE = /\b(\d{4}-\d{2}-\d{2}T[\d:.]+Z?)\b/;

/**
 * Best-effort classification. Deliberately broad: a missed rate limit surfaces
 * as a confusing hard failure, while a false positive costs only a wait that is
 * itself capped.
 */
export function detectRateLimit(text: string): RateLimitError | null {
  if (!RATE_LIMIT_RE.test(text)) return null;

  let resetsAt: Date | null = null;
  const epoch = RESET_EPOCH_RE.exec(text);
  const iso = RESET_ISO_RE.exec(text);
  if (epoch?.[1]) {
    resetsAt = new Date(Number(epoch[1]) * 1000);
  } else if (iso?.[1]) {
    const d = new Date(iso[1]);
    if (!Number.isNaN(d.getTime())) resetsAt = d;
  }
  if (resetsAt && Number.isNaN(resetsAt.getTime())) resetsAt = null;

  return new RateLimitError(text.trim().slice(0, 500), resetsAt);
}

interface StreamParse {
  result: Record<string, unknown> | null;
  lastAssistantUsage: Record<string, unknown> | null;
}

/**
 * Read the NDJSON stream, keeping the final `result` event and the usage block
 * of the last assistant message.
 */
function parseStream(stdout: string): StreamParse {
  let result: Record<string, unknown> | null = null;
  let lastAssistantUsage: Record<string, unknown> | null = null;

  for (const line of stdout.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed) continue;

    let event: unknown;
    try {
      event = JSON.parse(trimmed) as unknown;
    } catch {
      continue; // Non-JSON noise on stdout is not worth failing a turn over.
    }
    if (!isRecord(event)) continue;

    if (event['type'] === 'result') {
      result = event;
    } else if (event['type'] === 'assistant') {
      const message = event['message'];
      if (isRecord(message) && isRecord(message['usage'])) {
        lastAssistantUsage = message['usage'];
      }
    }
  }
  return { result, lastAssistantUsage };
}

/**
 * Live context occupancy, which drives session rotation.
 *
 * This must come from the **last assistant message**, not the result envelope.
 * The envelope's `usage` is aggregated across every API request in the turn, so
 * on a 28-iteration agentic turn its `cache_read_input_tokens` is a sum of 28
 * prompt reads and overstates context by more than an order of magnitude. The
 * final message's prompt size is the real occupancy. Cache reads count toward
 * it: cached tokens still fill the window.
 */
function extractUsage(
  envelope: Record<string, unknown>,
  lastAssistantUsage: Record<string, unknown> | null,
): ContextUsage | null {
  if (!lastAssistantUsage) return null;

  const promptTokens =
    num(lastAssistantUsage['input_tokens']) +
    num(lastAssistantUsage['cache_read_input_tokens']) +
    num(lastAssistantUsage['cache_creation_input_tokens']);

  const modelUsage = envelope['modelUsage'];
  let contextWindow = 0;
  if (isRecord(modelUsage)) {
    for (const entry of Object.values(modelUsage)) {
      if (isRecord(entry)) contextWindow = Math.max(contextWindow, num(entry['contextWindow']));
    }
  }

  if (promptTokens <= 0 || contextWindow <= 0) return null;
  return { promptTokens, contextWindow, ratio: promptTokens / contextWindow };
}

/**
 * `--json-schema` makes Claude return JSON in `result`, but a fenced code block
 * occasionally survives. Strip it rather than failing the whole run.
 */
export function parseStructured(text: string): unknown {
  let s = text.trim();
  const fence = /^```(?:json)?\s*\n([\s\S]*?)\n```$/.exec(s);
  if (fence?.[1]) s = fence[1].trim();
  try {
    return JSON.parse(s) as unknown;
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    throw new Error(
      `Expected schema-conformant JSON from claude but could not parse it: ${message}\n` +
        `--- raw ---\n${s.slice(0, 1500)}`,
    );
  }
}
